### ISSUE TITLE
Encoding::UndefinedConversionError: "\xFF" from ASCII-8BIT to UTF-8

### ISSUE THREAD

**Issue by Startouf** [gimite/google-drive-ruby#202]
I am trying to download a file from the gdrive to a temporary file, and use this file with Carrierwave uploader

My current code is 

```ruby
session = GoogleDrive.saved_session("config.json")
      file = session.file_by_url(url)
      ext = File.extname(file.title)
      sysfile = Tempfile.new(['tmpdownload', ext])
      file.download_to_file(sysfile)
      sysfile
end
```

What am I doing wrong ? Some SO questions mention this mention adding 'wb' to the file read mode, but I cannot do that from the library ?

The StackTrace
```
Encoding::UndefinedConversionError: "\xFF" from ASCII-8BIT to UTF-8
        from C:/Dev/Ruby23-x64/lib/ruby/2.3.0/delegate.rb:341:in `write'
        from C:/Dev/Ruby23-x64/lib/ruby/2.3.0/delegate.rb:341:in `block in delegating_block'
        from C:/Dev/Ruby23-x64/lib/ruby/gems/2.3.0/gems/google-api-client-0.9.8/lib/google/apis/core/download.rb:87:in `block (2 levels) in execute_once'
        from C:/Dev/Ruby23-x64/lib/ruby/gems/2.3.0/gems/hurley-0.2/lib/hurley/client.rb:314:in `receive_body'
        from C:/Dev/Ruby23-x64/lib/ruby/gems/2.3.0/gems/google-api-client-0.9.8/lib/google/apis/core/http_client_adapter.rb:19:in `block (2 levels) in call'
        from C:/Dev/Ruby23-x64/lib/ruby/gems/2.3.0/gems/httpclient-2.8.0/lib/httpclient.rb:1246:in `block in do_get_block'
        from C:/Dev/Ruby23-x64/lib/ruby/gems/2.3.0/gems/httpclient-2.8.0/lib/httpclient/session.rb:878:in `read_body_length'
        from C:/Dev/Ruby23-x64/lib/ruby/gems/2.3.0/gems/httpclient-2.8.0/lib/httpclient/session.rb:573:in `get_body'
        from C:/Dev/Ruby23-x64/lib/ruby/gems/2.3.0/gems/httpclient-2.8.0/lib/httpclient.rb:1243:in `do_get_block'
        from C:/Dev/Ruby23-x64/lib/ruby/gems/2.3.0/gems/httpclient-2.8.0/lib/httpclient.rb:1021:in `block in do_request'
        from C:/Dev/Ruby23-x64/lib/ruby/gems/2.3.0/gems/httpclient-2.8.0/lib/httpclient.rb:1129:in `protect_keep_alive_disconnected'
        from C:/Dev/Ruby23-x64/lib/ruby/gems/2.3.0/gems/httpclient-2.8.0/lib/httpclient.rb:1016:in `do_request'
        from C:/Dev/Ruby23-x64/lib/ruby/gems/2.3.0/gems/httpclient-2.8.0/lib/httpclient.rb:858:in `request'
        from C:/Dev/Ruby23-x64/lib/ruby/gems/2.3.0/gems/google-api-client-0.9.8/lib/google/apis/core/http_client_adapter.rb:17:in `block in call'
        from C:/Dev/Ruby23-x64/lib/ruby/gems/2.3.0/gems/hurley-0.2/lib/hurley/client.rb:252:in `initialize'
        from C:/Dev/Ruby23-x64/lib/ruby/gems/2.3.0/gems/google-api-client-0.9.8/lib/google/apis/core/http_client_adapter.rb:16:in `new'
```

**Comment by Startouf** [comment]
I have a workaround using the download_to_string method instead and using binmode + `wb+` read mode

```
def gdrive_download(url)
      session = GoogleDrive.saved_session("config.json")
      file = session.file_by_url(url)
      ext = File.extname(file.title)
      sysfile = Tempfile.new(['tmpdownload', ext])
      sysfile.binmode
      File.open(sysfile, 'wb+') do |fo|
        fo.write(file.download_to_string)
      end
      sysfile
    end
```

**Comment by gimite** [comment]
This would also work, I guess? (Just adding sysfile.binmode to your original code)

    session = GoogleDrive.saved_session("config.json")
    file = session.file_by_url(url)
    ext = File.extname(file.title)
    sysfile = Tempfile.new(['tmpdownload', ext])
    sysfile.binmode
    file.download_to_file(sysfile)
    sysfile
