### ISSUE TITLE
undefined method `css' for nil:NilClass"

### ISSUE THREAD

**Issue by alexmamonchik** [gimite/google-drive-ruby#228]
I have Sidekiq worker and update google document inside it. When I have several jobs at the same time I get error:
```bash
{"class"=>"CustomersWorker", "args"=>[415], "retry"=>2, "queue"=>"customers",
 "backtrace"=>true, "jid"=>"95630d8418b83c0163b951e2", "created_at"=>1472282082.205952, "enqueued_at"=>1472282102.349625, "error_message"=>"undefined method `css' for nil:NilClass", 
"error_class"=>"NoMethodError", "failed_at"=>1472282083.0361102, "retry_count"=>1, 
"error_backtrace"=>[
"/usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/google_drive-1.0.6/lib/google_drive/worksheet.rb:367:in `block in save'", 
"/usr/local/opt/rbenv/versions/2.1.2/lib/ruby/2.1.0/set.rb:263:in `each_key'", 
"/usr/local/opt/rbenv/versions/2.1.2/lib/ruby/2.1.0/set.rb:263:in `each'", 
"/usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/google_drive-1.0.6/lib/google_drive/worksheet.rb:364:in `save'",
 "/Users/alex/projects/easypaint-api/app/services/customers_service.rb:36:in `save_worksheet'",
 "/Users/alex/projects/easypaint-api/app/services/customers_service.rb:22:in `add_one_more'", 
"/Users/alex/projects/easypaint-api/app/workers/customers_worker.rb:7:in `perform'", 
"/usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/sidekiq-3.4.2/lib/sidekiq/processor.rb:75:in `execute_job'",
 "/usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/sidekiq-3.4.2/lib/sidekiq/processor.rb:52:in `block (2 levels) in process'",
 "/usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/sidekiq-3.4.2/lib/sidekiq/middleware/chain.rb:127:in `block in invoke'", 
"/Users/alex/projects/easypaint-api/lib/sidekiq_notification.rb:10:in `call'",
 "/usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/sidekiq-3.4.2/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'", 
"/usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/sidekiq-3.4.2/lib/sidekiq/middleware/server/active_record.rb:6:in `call'", 
"/usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/sidekiq-3.4.2/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'", 
"/usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/sidekiq-3.4.2/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'", 
"/usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/sidekiq-3.4.2/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'", 
"/usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/sidekiq-3.4.2/lib/sidekiq/middleware/server/logging.rb:15:in `block in call'",
 "/usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/sidekiq-3.4.2/lib/sidekiq/logging.rb:30:in `with_context'",
 "/usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/sidekiq-3.4.2/lib/sidekiq/middleware/server/logging.rb:11:in `call'", 
"/usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/sidekiq-3.4.2/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'",
 "/usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/sidekiq-3.4.2/lib/sidekiq/middleware/chain.rb:132:in `call'",
 "/usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/sidekiq-3.4.2/lib/sidekiq/middleware/chain.rb:132:in `invoke'",
 "/usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/sidekiq-3.4.2/lib/sidekiq/processor.rb:51:in `block in process'",
 "/usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/sidekiq-3.4.2/lib/sidekiq/processor.rb:98:in `stats'", 
"/usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/sidekiq-3.4.2/lib/sidekiq/processor.rb:50:in `process'",
 "/usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'", 
"/usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'", 
"/usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:122:in `dispatch'", 
"/usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'", 
"/usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'",
 "/usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'", 
"/usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'",
 "/usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'"], "retried_at"=>1472282103.4367821}
```

**Comment by gimite** [comment]
Sorry for late.

So you are writing to the same spreadsheet from multiple jobs at the same time? Then it may give the error you mentioned, in case "id" attribute of a cell changes when the sheet is updated (I'm not sure if that's the case, though). You may need to introduce a mutex lock so that save() method doesn't run at the same time for multiple jobs.

Anyway, if you try to write to a sheet from multiple jobs at the same time, you cannot expect which job "wins" i.e., which rewrite takes effect in the end. Is it really what you want?

**Comment by alexmamonchik** [comment]
thanks, yeah, looks like sometimes I have several jobs at the same time.

**Comment by gimite** [comment]
I see. It would still be better output a better error message, though...
