### ISSUE TITLE
JRUBY: java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by rahul8sharma** [gimite/google-drive-ruby#315]
Getting GC overhead limit memory error on more than 100 rows.

`session = get_session`
`file = session.file_by_url(request.parameters[:acdc_assessment][:file_url])`
`rows = file.worksheets.first.rows`

Error coming on this line "rows = file.worksheets.first.rows"

`Exception in thread "Ruby-0-Thread-5: /home/jombay/.rvm/gems/jruby-9.1.15.0/gems/puma-3.11.3-java/lib/puma/plugin.rb:64" Exception in thread "Ruby-0-Thread-12: /home/jombay/.rvm/gems/jruby-9.1.15.0/gems/puma-3.11.3-java/lib/puma/thread_pool.rb:241" Exception in thread "Ruby-0-Thread-11: /home/jombay/.rvm/gems/jruby-9.1.15.0/gems/puma-3.11.3-java/lib/puma/reactor.rb:152" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:57)
	at java.nio.ByteBuffer.allocate(ByteBuffer.java:335)
	at org.jruby.RubyEncoding$UTF8Coder.<init>(RubyEncoding.java:271)
	at org.jruby.RubyEncoding.getUTF8Coder(RubyEncoding.java:333)
	at org.jruby.RubyEncoding.decodeUTF8(RubyEncoding.java:248)
	at org.jruby.RubyString.getUnicodeValue(RubyString.java:5509)
	at org.jruby.RubyFile.stat(RubyFile.java:937)
	at org.jruby.RubyFile$INVOKER$s$1$0$stat.call(RubyFile$INVOKER$s$1$0$stat.gen)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:153)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:315)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:74)
	at org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:132)
	at org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:148)
	at org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:73)
	at org.jruby.runtime.Block.call(Block.java:124)
	at org.jruby.RubyProc.call(RubyProc.java:289)
	at org.jruby.RubyProc.call(RubyProc.java:246)
	at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:104)
	at java.lang.Thread.run(Thread.java:748)
java.lang.OutOfMemoryError: GC overhead limit exceeded
java.lang.OutOfMemoryError: Java heap space
Java::JavaLang::OutOfMemoryError: GC overhead limit exceeded
from org.apache.xml.utils.SuballocatedIntVector.<init>(SuballocatedIntVector.java:102)`

JRuby Version: jruby 9.1.15.0
Rails Version: Rails 5.0.6

**Comment by gimite** [comment]
Marked as dup of https://github.com/gimite/google-drive-ruby/issues/281.
