### ISSUE TITLE
LoadError: cannot load such file -- googleauth

### ISSUE THREAD

**Issue by tushar-eligible** [gimite/google-drive-ruby#328]
I am using google_drive gem in my project. 

Included in gem file:
gem "google_drive", "~> 2.0"

I am getting the following error. Please help.

LoadError: cannot load such file -- googleauth
/Users/tushar/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.5/lib/active_support/dependencies.rb:293:in `require'
/Users/tushar/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.5/lib/active_support/dependencies.rb:293:in `block in require'
/Users/tushar/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.5/lib/active_support/dependencies.rb:259:in `load_dependency'
/Users/tushar/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.5/lib/active_support/dependencies.rb:293:in `require'
/Users/tushar/.rvm/gems/ruby-2.4.1/gems/google_drive-2.1.2/lib/google_drive.rb:5:in `<top (required)>'
/Users/tushar/.rvm/gems/ruby-2.4.1/gems/bundler-1.17.1/lib/bundler/runtime.rb:81:in `require'
/Users/tushar/.rvm/gems/ruby-2.4.1/gems/bundler-1.17.1/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
/Users/tushar/.rvm/gems/ruby-2.4.1/gems/bundler-1.17.1/lib/bundler/runtime.rb:76:in `each'
/Users/tushar/.rvm/gems/ruby-2.4.1/gems/bundler-1.17.1/lib/bundler/runtime.rb:76:in `block in require'
/Users/tushar/.rvm/gems/ruby-2.4.1/gems/bundler-1.17.1/lib/bundler/runtime.rb:65:in `each'
/Users/tushar/.rvm/gems/ruby-2.4.1/gems/bundler-1.17.1/lib/bundler/runtime.rb:65:in `require'
/Users/tushar/.rvm/gems/ruby-2.4.1/gems/bundler-1.17.1/lib/bundler.rb:114:in `require'
/Users/tushar/Documents/Eligible/Security/security-console/config/application.rb:23:in `<top (required)>'
/Users/tushar/Documents/Eligible/Security/security-console/Rakefile:4:in `require_relative'
/Users/tushar/Documents/Eligible/Security/security-console/Rakefile:4:in `<top (required)>'
/Users/tushar/.rvm/gems/ruby-2.4.1/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/Users/tushar/.rvm/gems/ruby-2.4.1/gems/bundler-1.17.1/lib/bundler/cli/exec.rb:74:in `load'
/Users/tushar/.rvm/gems/ruby-2.4.1/gems/bundler-1.17.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
/Users/tushar/.rvm/gems/ruby-2.4.1/gems/bundler-1.17.1/lib/bundler/cli/exec.rb:28:in `run'
/Users/tushar/.rvm/gems/ruby-2.4.1/gems/bundler-1.17.1/lib/bundler/cli.rb:463:in `exec'
/Users/tushar/.rvm/gems/ruby-2.4.1/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/tushar/.rvm/gems/ruby-2.4.1/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/tushar/.rvm/gems/ruby-2.4.1/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/Users/tushar/.rvm/gems/ruby-2.4.1/gems/bundler-1.17.1/lib/bundler/cli.rb:27:in `dispatch'
/Users/tushar/.rvm/gems/ruby-2.4.1/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/Users/tushar/.rvm/gems/ruby-2.4.1/gems/bundler-1.17.1/lib/bundler/cli.rb:18:in `start'
/Users/tushar/.rvm/gems/ruby-2.4.1/gems/bundler-1.17.1/exe/bundle:30:in `block in <top (required)>'
/Users/tushar/.rvm/gems/ruby-2.4.1/gems/bundler-1.17.1/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/Users/tushar/.rvm/gems/ruby-2.4.1/gems/bundler-1.17.1/exe/bundle:22:in `<top (required)>'
/Users/tushar/.rvm/gems/ruby-2.4.1/bin/bundle:23:in `load'
/Users/tushar/.rvm/gems/ruby-2.4.1/bin/bundle:23:in `<main>'
/Users/tushar/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:24:in `eval'
/Users/tushar/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:24:in `<main>'
(See full trace by running task with --trace)

**Comment by tushar-eligible** [comment]
I have also used require "google_drive" and require "googleauth" but no luck

**Comment by gimite** [comment]
googleauth is a dependency of google_drive, so it should be installed if you install google_drive properly. Make sure that googleauth is installed in your environment. If not, maybe try installing it manually.

**Comment by raymondliversage** [comment]
require 'google_drive' returns: LoadError (cannot load such file -- google_drive):
please help!
Ruby 3.0.0
Rails 6.1.4
google-apis-core (0.4.1)
google-apis-drive_v3 (0.18.0)
google-apis-iamcredentials_v1 (0.7.0)
google-apis-sheets_v4 (0.11.0)
google-apis-storage_v1 (0.7.0)
google-cloud-core (1.6.0)
google-cloud-env (1.5.0)
google-cloud-errors (1.2.0)
google-cloud-storage (1.34.1)
google_drive (3.0.7)
googleauth (0.17.1)
