### ISSUE TITLE
Google::Apis::ServerError while downloading a file

### ISSUE THREAD

**Issue by ronzalo** [gimite/google-drive-ruby#346]
I have a worker who downloads a file from drive for later use, but it happens that about 30 seconds since the download starts, I throw the exception `Google::Apis::ServerError`

```ruby
session = GoogleDrive::Session.from_access_token(token)
file = session.file_by_id(file_id)
file.download_to_file "/tmp/myfile"
```

Relevant backtrace:

```
2019-08-14T20:05:59.170Z 25708 TID-1ai7z4 WARN: Google::Apis::ServerError: Server error
2019-08-14T20:05:59.170Z 25708 TID-1ai7z4 WARN: /home/deploy/my_application/shared/bundle/ruby/2.4.0/gems/google-api-client-0.30.5/lib/google/apis/core/http_command.rb:231:in `check_status'
/home/deploy/my_application/shared/bundle/ruby/2.4.0/gems/google-api-client-0.30.5/lib/google/apis/core/api_command.rb:118:in `check_status'
/home/deploy/my_application/shared/bundle/ruby/2.4.0/gems/google-api-client-0.30.5/lib/google/apis/core/download.rb:109:in `execute_once'
/home/deploy/my_application/shared/bundle/ruby/2.4.0/gems/google-api-client-0.30.5/lib/google/apis/core/http_command.rb:113:in `block (2 levels) in execute'
/home/deploy/my_application/shared/bundle/ruby/2.4.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
/home/deploy/my_application/shared/bundle/ruby/2.4.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
/home/deploy/my_application/shared/bundle/ruby/2.4.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
/home/deploy/my_application/shared/bundle/ruby/2.4.0/gems/google-api-client-0.30.5/lib/google/apis/core/http_command.rb:110:in `block in execute'
/home/deploy/my_application/shared/bundle/ruby/2.4.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
/home/deploy/my_application/shared/bundle/ruby/2.4.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
/home/deploy/my_application/shared/bundle/ruby/2.4.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
/home/deploy/my_application/shared/bundle/ruby/2.4.0/gems/google-api-client-0.30.5/lib/google/apis/core/http_command.rb:102:in `execute'
/home/deploy/my_application/shared/bundle/ruby/2.4.0/gems/google-api-client-0.30.5/lib/google/apis/core/base_service.rb:360:in `execute_or_queue_command'
/home/deploy/my_application/shared/bundle/ruby/2.4.0/gems/google-api-client-0.30.5/generated/google/apis/drive_v3/service.rb:1106:in `get_file'
/home/deploy/my_application/shared/bundle/ruby/2.4.0/gems/google_drive-3.0.3/lib/google_drive/file.rb:97:in `download_to_file'
```

**Comment by gimite** [comment]
What if you try again? Google Drive API is known to fail sometimes, and the workaround is to retry by yourself.

**Comment by ronzalo** [comment]
@gimite in fact it retries every time it fails, but it is curious that it fails about 30 seconds after the download has started

**Comment by gimite** [comment]
Do you mean it does succeed after retry?

**Comment by ronzalo** [comment]
nope, but it happened only with one file, so i think is a Drive problem
