### ISSUE TITLE
Error unknown keyword: supports_all_drives

### ISSUE THREAD

**Issue by mojobiri** [gimite/google-drive-ruby#384]
Hi. The following code started to generate exception recently:
```ruby
session = GoogleDrive.saved_session('config.json')
session.spreadsheet_by_key('sheet_key')
```
```
ArgumentError (unknown keyword: supports_all_drives)
/google_drive/session.rb:333:in `spreadsheet_by_key'
/google_drive/session.rb:288:in `file_by_id'
/ruby/2.6.0/gems/google-api-client-0.24.3/generated/google/apis/drive_v3/service.rb:777:in `get_file'
```

**Comment by mojobiri** [comment]
The issue happened after upgrade to 3.0.5 from 3.0.3
Version 3.0.3 works fine.

**Comment by frederickdubois** [comment]
Same here, had to specify 3.0.3 in my gemfile to stop receiving this error
